/**
 * Confirmation code handler — generates 3-layer confirmation codes.
 *
 * Hotel bookings have three separate confirmation code layers:
 * 1. CRS Confirmation: generated by booking channel (GDS/OTA), guest receives immediately
 * 2. PMS Confirmation: generated when reservation syncs to property system (may arrive async)
 * 3. Channel Confirmation: some OTAs generate their own additional code
 *
 * Multiple codes exist because CRS handles the sale, PMS handles the stay execution.
 * Separate audit trails.
 *
 * Domain source: OTAIP Lodging Knowledge Base §4 (Confirmation Codes — Three Layers)
 */

import type { HotelSource, HotelConfirmation } from '../types/hotel-common.js';

let confirmCounter = 0;

function generateCode(prefix: string): string {
  confirmCounter++;
  const random = Math.random().toString(36).substring(2, 10).toUpperCase();
  return `${prefix}-${random}${confirmCounter}`;
}

/**
 * Generate 3-layer confirmation codes for a booking.
 *
 * In v0.1.0 (mock), all three codes are generated synchronously.
 * In production:
 * - CRS confirmation is immediate
 * - PMS confirmation may arrive asynchronously (poll or webhook)
 * - Channel confirmation depends on the OTA
 */
export function generateConfirmationCodes(source: HotelSource): HotelConfirmation {
  return {
    crsConfirmation: generateCode('CRS'),
    pmsConfirmation: generateCode('PMS'),
    channelConfirmation: generateCode('CHN'),
    source,
  };
}

/** Reset counter (for testing). */
export function resetConfirmCounter(): void {
  confirmCounter = 0;
}
